### PR TITLE
add windows build

### PR DESCRIPTION
**Pull request by darikg**
cf conda-forge/fcl-feedstock#3

looks like libccd is the only fcl dependency that doesn't yet have a windows build

I have to admit, I barely know what I'm doing here, but it builds locally without error, so 🤞

### CODE REVIEW

**Comment by wolfv** [comment]
hey, cool, this is great!
Only thing left is to bump the build number to `1`.

**Comment by darikg** [comment]
bumped the build number and squashed everything

**Comment by wolfv** [comment]
great work!

**Comment by wolfv** [comment]
It'll take ~30 minutes until the final package appears on the conda-forge channel.

**Comment by darikg** [comment]
Thanks @wolfv! I'll try fcl once this shows up on conda-forge

**Pull request merged**
